export enum Color {
  Primary = "#313037",
  Primary_Light = "#5B5A62",
  Secondary = "#A8A8A8",
  White = "#FFFFFF",
  Gray = "#E7E7E7",
  Light = "#F7F7F7",
  Red = "#FC857F",
  Blue = "#D7E4FD",
  Green = "#CAEFF0",
  Orange = "#FEE9E2",
  Purple = "#F4EEFD",

  // Primary = "var(--primary)",
  // Primary_Light = "var(--primary-light)",
  // Secondary = "var(--secondary)",
  // White = "var(--white)",
  // Gray = "var(--gray)",
  // Light = "var(--light)",
  // Red = "var(--red)",
  // Blue = "var(--blue)",
  // Green = "var(--green)",
  // Orange = "var(--orange)",
  // Purple = "var(--purple)",
}
